tdData(
[{"i":1,"w":980,"h":349,"prefix":"wp-content/uploads/2015/11/Twin_Dragons_","numlen":3,"idxoffset":0,"ext":".png","pageUrl":"comic/the-beginning/","title":"The beginning (And maybe some apples too.)"},
{"i":2,"h":350,"pageUrl":"comic/wololoo/","title":"Wololoo (Enter code: Big Daddy)"},
{"i":3,"h":695,"pageUrl":"comic/imagination/","title":"Imagination (Kids ask the strangest questions)"},
{"i":4,"pageUrl":"comic/the-good-and-the-bad-news/","title":"The good and the bad news (Kaya runs on a daily dose of chocolate)"},
{"i":5,"pageUrl":"comic/game-time/","title":"Game time (You want some cocoa with that revenge?)"},
{"i":6,"pageUrl":"comic/ambition/","title":"Ambition (eeeexcellent)"},
{"i":7,"h":696,"pageUrl":"comic/memory/","title":"memory (To be honest, it's very good news if you don't need to leave the country)"},
{"i":8,"h":695,"pageUrl":"comic/feast/","title":"Feast (well, now we know where there allegiance really lies)"},
{"i":9,"h":356,"pageUrl":"comic/chicken/","title":"Chicken! (Put the cookie down!)"},
{"i":10,"h":695,"pageUrl":"comic/under-the-table-negotiation/","title":"Under the table negotiation (kickety kickety kick)"},
{"i":11,"h":356,"pageUrl":"comic/carrots/","title":"Carrots (The carrots are eeeeevil)"},
{"i":12,"h":695,"pageUrl":"comic/movie-night/","title":"Movie night (Why, hello there, miss Piggy)"},
{"i":13,"pageUrl":"comic/movie-night-outcome/","title":"Movie night outcome (snoooooore)"},
{"i":14,"pageUrl":"comic/packing/","title":"Packing (Do you even lift, dad)"},
{"i":15,"pageUrl":"comic/update-day/","title":"Update day (And unpack the webcam as well!)"},
{"i":16,"pageUrl":"comic/the-kaya-show/","title":"The Kaya show (Technically, it's not really PHOTObombing)"},
{"i":17,"prefix":"wp-content/uploads/2015/12/Twin_Dragons_","pageUrl":"comic/mission-start/","title":"Mission start (Revenge... revenge never changes)"},
{"i":18,"pageUrl":"comic/sneaky-sneak/","title":"Sneaky sneak (double O dragon)"},
{"i":19,"pageUrl":"comic/make-some-noise/","title":"Make some noise (If it was metal falling, it could be the newest Industrial song.)"},
{"i":20,"h":585,"prefix":"wp-content/uploads/2015/12/Twin_Dragons_019_","numlen":1,"idxoffset":-18,"pageUrl":"comic/happy-new-year/","title":"Happy New Year (BOOM BOOM scared dogs everywhere BOOM)"},
{"i":21,"h":695,"prefix":"wp-content/uploads/2016/01/Twin_Dragons_","numlen":3,"idxoffset":-1,"pageUrl":"comic/recalculating-route/","title":"Recalculating route (That's not an oil rig in the last panel, that's a windmill)"},
{"i":22,"pageUrl":"comic/wrapping-up/","title":"Wrapping up (wingardium leviosa)"},
{"i":23,"pageUrl":"comic/moon-person/","title":"Moon person (Hope that's not a permanent marker)"},
{"i":24,"pageUrl":"comic/artistic-urges/","title":"Artistic urges (full moon?)"},
{"i":25,"prefix":"wp-content/uploads/2016/02/Twin_Dragons_","pageUrl":"comic/moving-out/","title":"Moving out (I totally saw a parrot in the car next to us!)"},
{"i":26,"pageUrl":"comic/temperature-rising/","title":"Temperature rising (Kaya Outside-Map-Walker)"},
{"i":27,"pageUrl":"comic/caught/","title":"Caught (Maybe it was a drunk alien?)"},
{"i":28,"pageUrl":"comic/a-hidden-ally/","title":"A hidden ally (They never take the stealth route in a game for just this reason)"},
{"i":29,"pageUrl":"comic/first-looks/","title":"First looks (A \"little\" fixing up)"},
{"i":30,"prefix":"wp-content/uploads/2016/03/Twin_Dragons_","pageUrl":"comic/can-be-deceiving/","title":"Can be deceiving (You shut up, dad)"},
{"i":31,"pageUrl":"comic/exploration-mission/","title":"Exploration mission (Marco: \"Yeah, a little to the right, now drop them.\")"},
{"i":32,"pageUrl":"comic/greeting-the-neighbour/","title":"greeting the neighbour (ultimate technique, certain kill!)"},
{"i":33,"pageUrl":"comic/red-card/","title":"Red card (I'll just stalk the cans then)"},
{"i":34,"prefix":"wp-content/uploads/2016/04/Twin_Dragons_","pageUrl":"comic/mixed-signals/","title":"mixed signals (If only they threw chocolate at us instead.)"},
{"i":35,"pageUrl":"comic/sweet-meeting/","title":"Sweet meeting (Kaya + chocolate = happy dragon girl)"},
{"i":36,"pageUrl":"comic/chatter/","title":"chatter (and solving them, apparently)"},
{"i":37,"pageUrl":"comic/doofus/","title":"Doofus (doofus)"},
{"i":38,"prefix":"wp-content/uploads/2016/05/Twin_Dragons_","pageUrl":"comic/stake/","title":"Stake (Kaya speaking her mind again)"},
{"i":39,"pageUrl":"comic/moms-and-dads/","title":"Moms and dads (It's been a while since I've seen a 3 player splitscreen)"},
{"i":40,"pageUrl":"comic/being-positive/","title":"Being positive (*sad violin*)"},
{"i":41,"pageUrl":"comic/poodle/","title":"Poodle (Old-fashioned Benji now comes with a wig.)"},
{"i":42,"prefix":"wp-content/uploads/2016/05/Twin_Dragons_041-","numlen":1,"idxoffset":-41,"pageUrl":"comic/young-doggywan/","title":"young doggywan (Kaya still lost the match though...)"},
{"i":43,"prefix":"wp-content/uploads/2016/06/Twin_Dragons_","numlen":3,"idxoffset":-1,"pageUrl":"comic/explorer-units-return/","title":"Explorer units return (Kai and Kaya reporting for duty!)"},
{"i":44,"pageUrl":"comic/sweet-talk/","title":"Sweet talk (Her idol could very well be Willy Wonka)"},
{"i":45,"pageUrl":"comic/new-environment/","title":"New environment (dragging the sleeping bag closer in a not so subtle way)"},
{"i":46,"pageUrl":"comic/peacefull-dreams/","title":"Peacefull dreams (fwip fwip goes the tail)"},
{"i":47,"prefix":"wp-content/uploads/2016/07/Twin_Dragons_","pageUrl":"comic/snake-oil/","title":"Snake oil (yaaaaaaaaawn)"},
{"i":48,"pageUrl":"comic/mighty-bus/","title":"Mighty bus (vrooooom)"},
{"i":49,"pageUrl":"comic/buttons/","title":"Buttons (Why did you try the RED button?)"},
{"i":50,"pageUrl":"comic/city-school/","title":"City school (*high school noises*)"},
{"i":51,"prefix":"wp-content/uploads/2016/08/Twin_Dragons_","pageUrl":"comic/target-set/","title":"Target set (I'll be back)"},
{"i":52,"pageUrl":"comic/swoop/","title":"Swoop (Like an eagle!)"},
{"i":53,"pageUrl":"comic/off-to-a-good-start/","title":"Off to a good start (My favourite food is...)"},
{"i":54,"pageUrl":"comic/the-group/","title":"The group (I'm not a lizard!)"},
{"i":55,"pageUrl":"comic/scram/","title":"Scram (*sad violin*)"},
{"i":56,"prefix":"wp-content/uploads/2016/09/Twin_Dragons_","pageUrl":"comic/the-plan/","title":"The plan (initiate stealth mode)"},
{"i":57,"pageUrl":"comic/spying-commences/","title":"Spying commences (Except for that zebra girl, and every other person walking by)"},
{"i":58,"pageUrl":"comic/kaya-in-the-shadows/","title":"Kaya in the shadows (+2 sneaking leaf hat)"},
{"i":59,"pageUrl":"comic/engaging-target/","title":"Engaging target (The dragon has landed)"},
{"i":60,"prefix":"wp-content/uploads/2016/10/Twin_Dragons_","pageUrl":"comic/conversing/","title":"Conversing (Angry snake is angry)"},
{"i":61,"pageUrl":"comic/kayas-determination/","title":"Kaya’s determination (buuuurn baby burn)"},
{"i":62,"pageUrl":"comic/small-price/","title":"Small price (In the end, it's just burned paper)"},
{"i":63,"pageUrl":"comic/confused/","title":"Confused (Chibi Kaya doesn't understand)"},
{"i":64,"pageUrl":"comic/victory-hug/","title":"Victory hug (Tackle-hug!)"},
{"i":65,"prefix":"wp-content/uploads/2016/11/Twin_Dragons_","pageUrl":"comic/flashback-time/","title":"Flashback time (Snakes? In MY flashback!?)"},
{"i":66,"pageUrl":"comic/freebies/","title":"freebies (they got her to buy them a freaking gameboy!)"},
{"i":67,"pageUrl":"comic/a-change-of-fortune/","title":"A change of fortune (Snake is not amused)"},
{"i":68,"pageUrl":"comic/burned/","title":"Burned (Snake burn?)"},
{"i":69,"prefix":"wp-content/uploads/2016/12/Twin_Dragons_","pageUrl":"comic/keeping-an-eye-out/","title":"Keeping an eye out (Surveillance dragon)"},
{"i":70,"pageUrl":"comic/bestie/","title":"Bestie (Sleepy dragon, smiling snake)"},
{"i":71,"pageUrl":"comic/showdown-at-morning/","title":"Showdown at morning (*angry tail movements*)"},
{"i":72,"pageUrl":"comic/shove-ro-da/","title":"Shove ro da! (Dovahkiin, dovahkiin,...)"},
{"i":73,"prefix":"wp-content/uploads/2017/01/Twin_Dragons_","pageUrl":"comic/self-defense/","title":"Self Defense (A dragon doesn't need FIREarms)"},
{"i":74,"pageUrl":"comic/double-trouble/","title":"Double trouble (Through thick and thin... and detention it seems.)"},
{"i":75,"h":477,"prefix":"wp-content/uploads/2017/01/Twin_Dragons_073_2_extra","numlen":0,"idxoffset":-75,"pageUrl":"comic/extra-at-the-snackhouse/","title":"Extra: at the snackhouse (splurt)"},
{"i":76,"h":695,"prefix":"wp-content/uploads/2017/01/Twin_Dragons_","numlen":3,"idxoffset":-2,"pageUrl":"comic/breakfast-of-champions/","title":"Breakfast of champions (Good thing she didn't put the orange juice on the cornflakes.)"},
{"i":77,"pageUrl":"comic/kayas-club/","title":"Kaya’s club (carefull with the orange juice... never mind)"},
{"i":78,"prefix":"wp-content/uploads/2017/02/Twin_Dragons_","pageUrl":"comic/life-story/","title":"Life story (We will never know how she got that pancake from the ceiling)"},
{"i":79,"pageUrl":"comic/collission/","title":"Collision (To be honest, he should have watched where he was going.)"},
{"i":80,"pageUrl":"comic/a-wolf-in-basketball-clothes/","title":"A wolf in basketball clothes (What's this about exploding desserts?)"},
{"i":81,"pageUrl":"comic/about-species/","title":"About species (What would a shrimp hybrid look like?)"},
{"i":82,"prefix":"wp-content/uploads/2017/03/Twin_Dragons_","pageUrl":"comic/challenge-the-wolf/","title":"Challenge the wolf (*gloveslap in the face*)"},
{"i":83,"pageUrl":"comic/challenge-negotiations/","title":"Challenge negotiations (muhahahaha *howl to the moon*)"},
{"i":84,"pageUrl":"comic/challenge-accepted/","title":"Challenge accepted (*insert apropriate theme music here*)"},
{"i":85,"pageUrl":"comic/stay/","title":"Stay (Mad dragon + door = not a good combination)"},
{"i":86,"prefix":"wp-content/uploads/2017/04/Twin_Dragons_","pageUrl":"comic/missing-something/","title":"Missing something (Benji really doesn't see this going well.)"},
{"i":87,"pageUrl":"comic/recording/","title":"Recording (Does Cleo have a blackmail folder on her phone?)"},
{"i":88,"pageUrl":"comic/rising-star/","title":"Rising star (Cleo aspires to be a journalist?)"},
{"i":89,"pageUrl":"comic/reinforcements/","title":"Reinforcements (No daddy, I don't need a jacuzzi in my room.)"},
{"i":90,"h":766,"prefix":"wp-content/uploads/2017/05/Twin_Dragons_088_text","numlen":0,"idxoffset":-90,"pageUrl":"comic/hiring/","title":"Hiring (Don't carry me around. Hey!)"},
{"i":91,"h":695,"prefix":"wp-content/uploads/2017/05/Twin_Dragons_","numlen":3,"idxoffset":-2,"pageUrl":"comic/making-an-entrance/","title":"Making an entrance (bata bata bum tish)"},
{"i":92,"pageUrl":"comic/shabang/","title":"Shabang (Are you alive, Benji?)"},
{"i":93,"pageUrl":"comic/change-of-pace/","title":"Change of pace (Come on and slam, and welcome to the jam)"},
{"i":94,"pageUrl":"comic/dragon-thing/","title":"Dragon thing (Blushy dragon)"},
{"i":95,"prefix":"wp-content/uploads/2017/06/Twin_Dragons_","pageUrl":"comic/sprint/","title":"Sprint (vrooom)"},
{"i":96,"h":1145,"prefix":"wp-content/uploads/2017/06/Twin_Dragons_094_t-shirt","numlen":0,"idxoffset":-96,"pageUrl":"comic/gameplan/","title":"Gameplan (All secret and whispering)"},
{"i":97,"w":940,"h":1099,"prefix":"wp-content/uploads/2017/06/Twin_Dragons_095_tapastic_t-shirt","idxoffset":-97,"pageUrl":"comic/tough-love/","title":"Tough love (Beep Beep Kaya is a truck)"},
{"i":98,"w":980,"h":1145,"prefix":"wp-content/uploads/2017/06/Twin_Dragons_096_preorder","idxoffset":-98,"pageUrl":"comic/day-of-resting/","title":"Day of resting (Day of resting)"},
{"i":99,"prefix":"wp-content/uploads/2017/07/Twin_Dragons_097_preorder","idxoffset":-99,"pageUrl":"comic/rolling/","title":"Rolling (Hope for a natural 20)"},
{"i":100,"prefix":"wp-content/uploads/2017/07/Twin_Dragons_098_preorder","idxoffset":-100,"pageUrl":"comic/hot-development/","title":"Hot development (coincidentally, Kaya likes the Red Hot Chilli Peppers)"},
{"i":101,"prefix":"wp-content/uploads/2017/07/Twin_Dragons_099_preorder","idxoffset":-101,"pageUrl":"comic/short-jokes/","title":"Short jokes (Kaya also got in trouble for it already, you don't want to make it a tradition, do you?)"},
{"i":102,"h":695,"prefix":"wp-content/uploads/2017/07/Twin_Dragons_","numlen":3,"idxoffset":-2,"pageUrl":"comic/debt/","title":"Debt (Ever heard of privacy, Cleo?)"},
{"i":103,"pageUrl":"comic/branding/","title":"Branding (No, Tommy Gecko is not a hybrid himself)"},
{"i":104,"prefix":"wp-content/uploads/2017/08/Twin_Dragons_","pageUrl":"comic/spicy-drink/","title":"Spicy drink (Can it even make the water taste different like that?)"},
{"i":105,"pageUrl":"comic/start-game/","title":"Start game (Gotta go fast! But not too fast...)"},
{"i":106,"pageUrl":"comic/slap/","title":"slap (Tails are not stated in the rulebook)"},
{"i":107,"pageUrl":"comic/one-point/","title":"one point (jumping dragons, batman!)"},
{"i":108,"prefix":"wp-content/uploads/2017/09/Twin_Dragons_","pageUrl":"comic/unfair/","title":"Unfair (One surprised wolf, coming right up)"},
{"i":109,"pageUrl":"comic/fetch/","title":"fetch (Some running is in order)"},
{"i":110,"pageUrl":"comic/flying-point/","title":"Flying point (I believe I can fly...)"},
{"i":111,"pageUrl":"comic/putting-the-evil-in-basketball/","title":"Putting the evil in basketball (Rex should auditon as a Disney villain...)"},
{"i":112,"prefix":"wp-content/uploads/2017/10/Twin_Dragons_","pageUrl":"comic/beast/","title":"Beast (Wardrums playing)"},
{"i":113,"pageUrl":"comic/recap/","title":"Recap (Wolf dunk!)"},
{"i":114,"pageUrl":"comic/great-advice/","title":"Great advice (Do we have a plan B? Or any other letter?)"},
{"i":115,"pageUrl":"comic/struggle/","title":"Struggle (A bit one-sided, don't you think?)"},
{"i":116,"pageUrl":"comic/downfall/","title":"Downfall (Rex DOES seem to watch a certain anime)"},
{"i":117,"prefix":"wp-content/uploads/2017/11/Twin_Dragons_","pageUrl":"comic/water-drills/","title":"Water drills (Tired dragon is tired... and confused)"},
{"i":118,"pageUrl":"comic/reasoning/","title":"Reasoning (Better start shutting up, Nate)"},
{"i":119,"pageUrl":"comic/seriously/","title":"seriously (Kaya on sleeve duty)"},
{"i":120,"pageUrl":"comic/doggy-captain/","title":"doggy captain (Someone got found out...)"},
{"i":121,"prefix":"wp-content/uploads/2017/12/Twin_Dragons_","pageUrl":"comic/catacombs-and-drakes/","title":"Catacombs and Drakes (This is mandatory knowledge for a dragon, you know.)"},
{"i":122,"pageUrl":"comic/grumpy-wolf/","title":"Grumpy wolf (Benji: Ack! my sandwich!)"},
{"i":123,"pageUrl":"comic/presumptions-shattered/","title":"presumptions shattered (How many editions of the C&D rulebook are there anyway?)"},
{"i":124,"pageUrl":"comic/game-night/","title":"Game night (It's a pretty nice hat too!)"},
{"i":125,"prefix":"wp-content/uploads/2018/01/Twin_Dragons_","pageUrl":"comic/last-player/","title":"Last player (Who does homework nowadays?)"},
{"i":126,"prefix":"wp-content/uploads/2018/01/Twin_Dragons_124-","numlen":1,"idxoffset":-125,"pageUrl":"comic/limited-knowledge/","title":"Limited knowledge (Wolf depending on the dog)"},
{"i":127,"prefix":"wp-content/uploads/2018/01/Twin_Dragons_","numlen":3,"idxoffset":-2,"pageUrl":"comic/listen-closely/","title":"Listen closely (Or not, that's also an option)"},
{"i":128,"pageUrl":"comic/goody-two-shoes/","title":"goody two-shoes (Benji has a good memory)"},
{"i":129,"pageUrl":"comic/ulterior-motive/","title":"Ulterior motive (WHACK!)"},
{"i":130,"prefix":"wp-content/uploads/2018/02/Twin_Dragons_","pageUrl":"comic/healer-power/","title":"Healer power (It doesn't mean you're pocket-sized, Cleo)"},
{"i":131,"pageUrl":"comic/party-reveal/","title":"Party reveal (Salary negotiations with a snake)"},
{"i":132,"pageUrl":"comic/rat-plague/","title":"Rat plague (Maybe your strongest spell wasn't such a good idea, Kaya)"},
{"i":133,"pageUrl":"comic/persuasion-check/","title":"Persuasion check (partners in crime)"},
{"i":134,"prefix":"wp-content/uploads/2018/03/Twin_Dragons_","pageUrl":"comic/destructive-talent/","title":"destructive talent (SHRUBBERY!)"},
{"i":135,"pageUrl":"comic/crystal-duck/","title":"Crystal duck (quack!)"},
{"i":136,"pageUrl":"comic/watch-your-step/","title":"Watch your step (Shhh! Kaya! Fall quietly!)"},
{"i":137,"pageUrl":"comic/encounter/","title":"Encounter (This might be a little overkill, Benji)"},
{"i":138,"prefix":"wp-content/uploads/2018/04/Twin_Dragons_","pageUrl":"comic/shadow-dragon/","title":"Shadow Dragon (Puny wooden beam no match for strong dragon!)"},
{"i":139,"pageUrl":"comic/dice-rule/","title":"Dice rule (whimsical hammer)"},
{"i":140,"pageUrl":"comic/shield-block/","title":"shield block (Kai has it easy, with his shadowstep...)"},
{"i":141,"pageUrl":"comic/bubble/","title":"bubble (What do shield noises even sound like?)"},
{"i":142,"pageUrl":"comic/behind-door-number-one/","title":"Behind door number one (Kaya hug, rolled critical success)"},
{"i":143,"prefix":"wp-content/uploads/2018/05/Twin_Dragons_","pageUrl":"comic/moral-choices/","title":"Moral choices (LOVE = Level Of ViolencE?)"},
{"i":144,"pageUrl":"comic/heated-argument/","title":"Heated argument (Kaya really isn't one to be outdone so easily)"},
{"i":145,"pageUrl":"comic/can-i-have-it/","title":"Can I have it? (I'm obviously summoning something, can't you see the pentagram I painted on the wall!)"},
{"i":146,"pageUrl":"comic/hammer-time/","title":"Hammer time (we COULD have tried reasoning with him, but I had a hammer...)"},
{"i":147,"prefix":"wp-content/uploads/2018/06/Twin_Dragons_","pageUrl":"comic/demolition-expertise/","title":"Demolition expertise (Demolition expertise)"},
{"i":148,"pageUrl":"comic/magic-user/","title":"Magic user (Wakataka dragon missile!)"},
{"i":149,"pageUrl":"comic/chaotic-save/","title":"Chaotic save (These meddling kids!)"},
{"i":150,"pageUrl":"comic/the-wolf-and-the-hammer/","title":"The wolf and the hammer (wolf-shield noises)"},
{"i":151,"prefix":"wp-content/uploads/2018/07/Twin_Dragons_","pageUrl":"comic/minor-setback/","title":"Minor setback (evil_laughter.exe)"},
{"i":152,"pageUrl":"comic/the-crystal-duck-at-last/","title":"The crystal duck at last (Kaya too fast for the dice)"},
{"i":153,"pageUrl":"comic/penguin/","title":"Penguin (Sorry if you expected a rolling ball or living bird statues :p)"},
{"i":154,"pageUrl":"comic/betrayal/","title":"Betrayal (If it wasn't for that meddling penguin!)"},
{"i":155,"pageUrl":"comic/dont-get-lost/","title":"Don’t get lost (BRRRRRRM the sound of a cave collapsing.)"},
{"i":156,"prefix":"wp-content/uploads/2018/08/Twin_Dragons_","pageUrl":"comic/leap/","title":"Leap (I can only grant 5 out of 10 due to the landing)"},
{"i":157,"pageUrl":"comic/handsome-reward/","title":"Handsome reward (The wolf paladin has it's own alignment)"},
{"i":158,"pageUrl":"comic/smuggling/","title":"Smuggling (I have no idea how paladin wolf clobbering sounds any different from a regular clobbering though)"},
{"i":159,"pageUrl":"comic/loose-ends/","title":"Loose ends (Benji is such a good dog)"},
{"i":160,"prefix":"wp-content/uploads/2018/09/Twin_Dragons_","pageUrl":"comic/buds-now/","title":"Buds now (Would petting Benji on the head be weird?)"},
{"i":161,"pageUrl":"comic/day-at-the-museum/","title":"Day at the museum (Excited Kaya is excited!)"},
{"i":162,"pageUrl":"comic/shedding/","title":"Shedding (No, they don't grow wings later in their life)"},
{"i":163,"pageUrl":"comic/walrus/","title":"Walrus (Not your average horror movie animal)"},
{"i":164,"prefix":"wp-content/uploads/2018/10/Twin_Dragons_","pageUrl":"comic/t-rex/","title":"T-rex (Jurassic park theme intensifies)"},
{"i":165,"pageUrl":"comic/photoshoot/","title":"Photoshoot (Cleo is pretty good with the camera)"},
{"i":166,"pageUrl":"comic/knight-in-furry-armour/","title":"Knight in furry armour (Yes, Nate's life purpose is to annoy Rex)"},
{"i":167,"pageUrl":"comic/another-t-rex/","title":"Another T-Rex (Cleo at peak comedy performance)"},
{"i":168,"pageUrl":"comic/wolf-exhibit/","title":"Wolf exhibit (Yeah, okay, I like wolves, can we get over this now?)"},
{"i":169,"prefix":"wp-content/uploads/2018/11/Twin_Dragons_","pageUrl":"comic/positive-blackmail/","title":"Positive blackmail (No worries, Cleo is only slightly offended)"},
{"i":170,"pageUrl":"comic/mess-with-the-wrong-snake/","title":"Mess with the wrong snake (Dad, I need you to start a small crusade, starting with this painting I'm standing in front of. Okay, I'll call back when you're out of the meeting.)"},
{"i":171,"pageUrl":"comic/gem-store/","title":"Gem store (And you all thought Kaya would be the one flipping out over the gems)"},
{"i":172,"pageUrl":"comic/the-mask/","title":"The mask (Make sure to aim away from the WOODEN and HIGHLY FLAMMABLE masks, Kai)"},
{"i":173,"prefix":"wp-content/uploads/2018/12/Twin_Dragons_171-","numlen":1,"idxoffset":-172,"pageUrl":"comic/cowardly-wolf/","title":"Cowardly wolf (Stupid dog, you made me look bad)"},
{"i":174,"prefix":"wp-content/uploads/2018/12/Twin_Dragons_","numlen":3,"idxoffset":-2,"pageUrl":"comic/raptor-room/","title":"Raptor room (Personal space is not a concept Kaya is familiar with)"},
{"i":175,"pageUrl":"comic/the-three-witches/","title":"The three witches (A flock of crows is circling the museum as we speak)"},
{"i":176,"pageUrl":"comic/hidden-content/","title":"Hidden content (I guess a firebreathing lizard is still a lizard...)"},
{"i":177,"pageUrl":"comic/dragon-save/","title":"Dragon save (Time to save my best friend! Still take my drink though.)"},
{"i":178,"prefix":"wp-content/uploads/2019/01/Twin_Dragons_","pageUrl":"comic/chocolate-casualty/","title":"Chocolate casualty (And the Darwin award goes to...)"},
{"i":179,"pageUrl":"comic/superior-numbers/","title":"Superior numbers (How does it feel to be the one being ganged up on instead...)"},
{"i":180,"pageUrl":"comic/safety-returns/","title":"Safety returns (Store clerk sees Kaya entering the store again and goes on break at the exact same moment.)"},
{"i":181,"pageUrl":"comic/great-sir-wolf/","title":"Great sir wolf (Tsun Rex)"},
{"i":182,"prefix":"wp-content/uploads/2019/02/Twin_Dragons_","pageUrl":"comic/holding-a-grudge/","title":"Holding a grudge (That's one stubborn vulture...)"},
{"i":183,"pageUrl":"comic/throwing-arm/","title":"Throwing arm (Listen to the blonde for once!)"},
{"i":184,"pageUrl":"comic/sleight-of-hand/","title":"Sleight of hand (Larissa should get a grip...)"},
{"i":185,"pageUrl":"comic/club-benefits/","title":"Club benefits (Menacing aura)"},
{"i":186,"prefix":"wp-content/uploads/2019/03/Twin_Dragons_","pageUrl":"comic/a-fair-proposition/","title":"A fair proposition (Give him some time and he will find out what your shoe size is as well...)"},
{"i":187,"pageUrl":"comic/consequences/","title":"Consequences (And thus, the witch was led to the stake...)"},
{"i":188,"pageUrl":"comic/bailing-her-out/","title":"Bailing her out (Nate salutes you, random security guard!)"},
{"i":189,"pageUrl":"comic/gratitude/","title":"Gratitude (Even Nate can't figure this out)"},
{"i":190,"prefix":"wp-content/uploads/2019/04/Twin_Dragons_","pageUrl":"comic/blondie/","title":"Blondie (Nate: It was her credit card? Lizzy: WILL YOU LISTEN!!!)"},
{"i":191,"pageUrl":"comic/good-intentions/","title":"Good intentions (Deep down, she might have known, but peer pressure...)"},
{"i":192,"pageUrl":"comic/souvenir-shop/","title":"Souvenir shop (Got Tiki? What's Tiki?)"},
{"i":193,"pageUrl":"comic/t-rex-shirt/","title":"T-Rex-shirt (Cleo? Interested in snakes? Naaaah xD)"},
{"i":194,"h":1390,"prefix":"wp-content/uploads/2019/04/Twin_Dragons_192-","idxoffset":-1,"pageUrl":"comic/realisations/","title":"Realisations (Luckily the penguins in the back are fake. imagine how awkward that would be.)"},
{"i":195,"h":695,"prefix":"wp-content/uploads/2019/05/Twin_Dragons_194-","numlen":1,"idxoffset":-194,"pageUrl":"comic/the-girl-who-blamed-the-wolf/","title":"The girl who blamed the wolf (Fairy tales? More like 'dragon tales')"},
{"i":196,"prefix":"wp-content/uploads/2019/05/Twin_Dragons_","numlen":3,"idxoffset":-1,"pageUrl":"comic/evasive-actions/","title":"Evasive actions (Push little snek!)"},
{"i":197,"pageUrl":"comic/hair-color/","title":"Hair color (Shiny Benji)"},
{"i":198,"pageUrl":"comic/restaurant/","title":"Restaurant (Marco has a very unique way of doing things)"},
{"i":199,"prefix":"wp-content/uploads/2019/06/Twin_Dragons_","pageUrl":"comic/an-apple-a-day/","title":"An apple a day (Yes, he basically bit an apple in half)"},
{"i":200,"pageUrl":"comic/skipping-school/","title":"Skipping school (When your dad helps you skip school as fast as possible)"},
{"i":201,"pageUrl":"comic/underwear/","title":"Underwear (Raspberry jam and fur sandwich)"},
{"i":202,"pageUrl":"comic/back-seat-calling/","title":"Back seat calling (Alex? Why not Jeeves or Sebastian?)"},
{"i":203,"prefix":"wp-content/uploads/2019/07/Twin_Dragons_","pageUrl":"comic/species/","title":"Species (Kaya is impressed with everything.)"},
{"i":204,"pageUrl":"comic/liftoff/","title":"Liftoff (Going up!)"},
{"i":205,"pageUrl":"comic/waiting-room/","title":"Waiting room (What about the kid with the broken leg? He's on file already, he can wait a little.)"},
{"i":206,"prefix":"wp-content/uploads/2019/07/Twin_Dragons_205-","numlen":1,"idxoffset":-205,"pageUrl":"comic/the-gown/","title":"The gown (Hey! Listen! Hey!)"},
{"i":207,"prefix":"wp-content/uploads/2019/07/Twin_Dragons_","numlen":3,"idxoffset":-1,"pageUrl":"comic/move-it/","title":"Move it (I like to move it move it!)"},
{"i":208,"prefix":"wp-content/uploads/2019/08/Twin_Dragons_","pageUrl":"comic/laces/","title":"Laces (Twin connection strikes again)"},
{"i":209,"pageUrl":"comic/confidence-ruffle/","title":"Confidence ruffle (The hairdo of confidence!)"},
{"i":210,"pageUrl":"comic/meeting-the-doctor/","title":"Meeting the doctor (Maybe he's behind on schedule?)"},
{"i":211,"pageUrl":"comic/dra-hon/","title":"Dra-hon! (Not to be confused with a durahan)"},
{"i":212,"prefix":"wp-content/uploads/2019/09/Twin_Dragons_","pageUrl":"comic/you-can-be-a-dragon/","title":"You can be a dragon (I'm sure you are the next king under the mountain)"},
{"i":213,"prefix":"wp-content/uploads/2019/09/Twin_Dragons_212-","numlen":1,"idxoffset":-212,"pageUrl":"comic/pretty-please/","title":"Pretty please (This isn't even her full power...)"},
{"i":214,"prefix":"wp-content/uploads/2019/09/Twin_Dragons_","numlen":3,"idxoffset":-1,"pageUrl":"comic/temperature-check/","title":"Temperature check (One of these temperatures is the right one.)"},
{"i":215,"pageUrl":"comic/demonstration/","title":"Demonstration (Please keep your distance while I'm being a flamethrower)"},
{"i":216,"prefix":"wp-content/uploads/2019/09/Twin_Dragons_215-","numlen":1,"idxoffset":-215,"pageUrl":"comic/mythical/","title":"Mythical (Time for some explanations!)"},
{"i":217,"prefix":"wp-content/uploads/2019/10/Twin_Dragons_","numlen":3,"idxoffset":-1,"pageUrl":"comic/finallyadragon/","title":"Finally a dragon (Smug is the default reaction right now, doc.)"},
{"i":218,"pageUrl":"comic/continue-examination/","title":"Continue examination (Yes, that's an extension for larger ears)"},
{"i":219,"pageUrl":"comic/mechanism/","title":"Mechanism (Always be gentle while handling ears, especially if they're as big as this)"},
{"i":220,"pageUrl":"comic/reflex-test/","title":"Reflex test (Reflex test)"},
{"i":221,"prefix":"wp-content/uploads/2019/11/Twin_Dragons_","pageUrl":"comic/heavy/","title":"Heavy (Kaya strong!)"},
{"i":222,"pageUrl":"comic/again-with-the-bearded-dragon/","title":"Again with the bearded dragon (A beard is flamable, no beard!)"},
{"i":223,"pageUrl":"comic/controlled-hazard/","title":"Controlled hazard (Still quite a flame, though)"},
{"i":224,"pageUrl":"comic/subtle-pyromancy/","title":"Subtle pyromancy (Surprisingly, her hair resisted quite well.)"},
{"i":225,"prefix":"wp-content/uploads/2019/12/Twin_Dragons_","pageUrl":"comic/unicorn/","title":"Unicorn (Asian parent: \"He is a doctor. What do you mean that's not a species?\")"},
{"i":226,"pageUrl":"comic/vocal-test/","title":"Vocal test (Do not run from Kaya's fiery enthusiasm)"},
{"i":227,"pageUrl":"comic/best-effort/","title":"Best effort (A friendly ELBOW INTO THE RIBS!)"},
{"i":228,"pageUrl":"comic/airhead/","title":"Airhead (Air is also flammable in the right conditions)"},
{"i":229,"pageUrl":"comic/volatile/","title":"Volatile (Spit shine gets a whole different meaning...)"},
{"i":230,"prefix":"wp-content/uploads/2020/01/Twin_Dragons_","pageUrl":"comic/spitfire/","title":"Spitfire (I mean, there has to be a little spit in there, right?)"},
{"i":231,"pageUrl":"comic/measurements/","title":"Measurements (Stop flapping your ears, it affects the scale!)"},
{"i":232,"pageUrl":"comic/weighty-discussion/","title":"Weighty discussion (She doesn't eat THAT much chocolate. Right?)"},
{"i":233,"pageUrl":"comic/shiver/","title":"Shiver (Be sure to read Kaya's freestyle rap in the description :p)"},
{"i":234,"prefix":"wp-content/uploads/2020/02/Twin_Dragons_","pageUrl":"comic/tail-length/","title":"Tail length (Kai's hair is just really really long. All the way to the tip of his tail xD)"},
{"i":235,"pageUrl":"comic/scales/","title":"Scales (The doctor back then was flamed several times, and rightfully so.)"},
{"i":236,"pageUrl":"comic/difficulty-rating/","title":"Difficulty rating (Defenses have been breached!)"},
{"i":237,"pageUrl":"comic/target-spotted/","title":"Target spotted (KayaOS: Target acquired)"},
{"i":238,"prefix":"wp-content/uploads/2020/03/Twin_Dragons_","pageUrl":"comic/youch/","title":"Youch (yoink :p)"},
{"i":239,"pageUrl":"comic/remorse/","title":"Remorse (Healing hugs!)"},
{"i":240,"pageUrl":"comic/approved/","title":"Approved (Kai had Kaya pinned for a moment)"},
{"i":241,"pageUrl":"comic/sweet-reward/","title":"Sweet reward (fourth panel: Why is there no candy in my mouth?)"},
{"i":242,"pageUrl":"comic/lab-samples/","title":"Lab samples (Hey Arnold!)"},
{"i":243,"prefix":"wp-content/uploads/2020/04/Twin_Dragons_","pageUrl":"comic/tapped-wire/","title":"Tapped wire (The phone is compromised)"},
{"i":244,"pageUrl":"comic/the-waiting-is-over/","title":"The waiting is over (Fur dye can be addictive :p)"},
{"i":245,"prefix":"wp-content/uploads/2020/04/Twin_Dragons_244b","numlen":0,"idxoffset":-245,"pageUrl":"comic/relief-cycle/","title":"Relief cycle (Kaya is now also a professional barber xD)"},
{"i":246,"prefix":"wp-content/uploads/2020/04/Twin_Dragons_","numlen":3,"idxoffset":-1,"pageUrl":"comic/experiment/","title":"Experiment (Angry Italian noises!)"},
{"i":247,"h":1390,"prefix":"wp-content/uploads/2020/05/Twin_Dragons_246-247-","numlen":1,"idxoffset":-246,"pageUrl":"comic/meet-jin/","title":"Meet Jin (Polite boy is polite)"},
{"i":248,"h":695,"prefix":"wp-content/uploads/2020/05/Twin_Dragons_","numlen":3,"idxoffset":0,"pageUrl":"comic/komainu/","title":"Komainu (he's a mythical guard dog)"},
{"i":249,"pageUrl":"comic/little-guardian/","title":"Little guardian (Jin protecc!)"},
{"i":250,"pageUrl":"comic/traitor/","title":"Traitor (Kai can be a little evil as well :p)"},
{"i":251,"prefix":"wp-content/uploads/2020/06/Twin_Dragons_","pageUrl":"comic/tower-down/","title":"Tower down (Urge to kill... rising!)"},
{"i":252,"pageUrl":"comic/dragon-feud/","title":"Dragon feud (Marco, settler of dragon disputes)"},
{"i":253,"pageUrl":"comic/katsumi/","title":"Katsumi (Little guardian, big guardian)"},
{"i":254,"prefix":"wp-content/uploads/2020/06/Twin_Dragons_253-","numlen":1,"idxoffset":-253,"pageUrl":"comic/fireproofing-101/","title":"Fireproofing 101 (Maybe we should get some paper tissues...)"},
{"i":255,"prefix":"wp-content/uploads/2020/06/Twin_Dragons_","numlen":3,"idxoffset":0,"pageUrl":"comic/chicken-soup/","title":"Chicken soup (Nurse Kaya on duty!)"},
{"i":256,"prefix":"wp-content/uploads/2020/07/Twin_Dragons_","pageUrl":"comic/little-dragon/","title":"Little dragon (A dragon for a dragon)"},
{"i":257,"pageUrl":"comic/drifting-off/","title":"Drifting off (Dragon Dream Land)"},
{"i":258,"pageUrl":"comic/monkey-business/","title":"Monkey business (Kee kee kee!)"},
{"i":259,"pageUrl":"comic/dreaming/","title":"Dreaming (If you think that, after last week's 'Kee kee kee', I'm going to put 'Eek eek!' in here, you are right!)"},
{"i":260,"prefix":"wp-content/uploads/2020/08/Twin_Dragons_","pageUrl":"comic/prophecy/","title":"Prophecy (Cleo: Kage bunshin no jutsu!)"},
{"i":261,"pageUrl":"comic/weather-system/","title":"Weather system (The village doesn't have the most original naming sense, okay)"},
{"i":262,"pageUrl":"comic/hear-ye-hear-ye/","title":"Hear ye hear ye (Gotta make sure the town knows of this!)"},
{"i":263,"pageUrl":"comic/gathering-attention/","title":"Gathering attention (Never again, I said as I finished this crowd scene. Until the next time I need one, I immediately thought xD)"},
{"i":264,"pageUrl":"comic/yeet/","title":"Yeet (Our belief system tells us to take the scenic route)"},
{"i":265,"prefix":"wp-content/uploads/2020/09/Twin_Dragons_","pageUrl":"comic/another-familiar-face/","title":"Another familiar face (Roar! goes the puppy)"},
{"i":266,"pageUrl":"comic/guardian-challenge/","title":"Guardian challenge (Don't worry, I'm sure the challenges will be fair.)"},
{"i":267,"pageUrl":"comic/dance-lion/","title":"Dance lion (Busting some moves!)"},
{"i":268,"pageUrl":"comic/dragon-dance/","title":"Dragon Dance (Every dream I'm shuffling)"},
{"i":269,"prefix":"wp-content/uploads/2020/10/Twin_Dragons_","pageUrl":"comic/second-challenge/","title":"Second challenge (Someone's a sore loser)"},
{"i":270,"pageUrl":"comic/puzzling/","title":"Puzzling (Possibly a world record in his dream?)"},
{"i":271,"pageUrl":"comic/stairway-to-heavens-palace/","title":"Stairway to Heaven’s Palace (The party grows once again)"},
{"i":272,"pageUrl":"comic/meeting-the-goddess/","title":"Meeting the goddess (Smoll Kaya is smoll)"},
{"i":273,"prefix":"wp-content/uploads/2020/11/Twin_Dragons_","pageUrl":"comic/high-stakes/","title":"High stakes (Dragon vs dragon)"},
{"i":274,"pageUrl":"comic/chess/","title":"Chess (Prepare to see a master at work!)"},
{"i":275,"pageUrl":"comic/fools-mate/","title":"Fool’s mate (Fool's mate is the fastest way possible to win at chess)"},
{"i":276,"pageUrl":"comic/there-there/","title":"There there (*innocent whistling in the distance*)"},
{"i":277,"pageUrl":"comic/saving-the-goddess/","title":"Saving the goddess (*Happy Scarabath noises*)"},
{"i":278,"prefix":"wp-content/uploads/2020/12/Twin_Dragons_","pageUrl":"comic/making-it-rain/","title":"Making it rain (ORA ORA ORA ORA ORA ORA ORA ORA ORA ORA)"},
{"i":279,"pageUrl":"comic/nice-weather/","title":"Nice weather (It's raining. That's what you wanted, right?)"},
{"i":280,"pageUrl":"comic/time-to-wake-up/","title":"Time to wake up (Let's see if you get the reference from the title of this page :p)"},
{"i":281,"pageUrl":"comic/as-it-was-told/","title":"As it was told (And what a dream it was!)"},
{"i":282,"prefix":"wp-content/uploads/2021/01/Twin_Dragons_","pageUrl":"comic/troubled-morning/","title":"Troubled morning (Kai is cured again :D)"},
{"i":283,"pageUrl":"comic/worried-dragon/","title":"Worried dragon (Pat the dragon)"},
{"i":284,"pageUrl":"comic/bus-talk/","title":"Bus talk (Kaya can still sleep anywhere)"},
{"i":285,"pageUrl":"comic/generous-snake/","title":"Generous snake (I wonder how many times she had to apologize to the bus driver already)"},
{"i":286,"prefix":"wp-content/uploads/2021/02/Twin_Dragons_","pageUrl":"comic/snakey-solutions/","title":"Snakey solutions (Cleo will come up with something.)"},
{"i":287,"pageUrl":"comic/pon-pon/","title":"Pon pon (Yes, Cleo has her butler Alex holding her phone for her)"},
{"i":288,"pageUrl":"comic/dragon-sharks/","title":"Dragon sharks (Not pictured: Kaya actually jumping up and biting the air)"},
{"i":289,"pageUrl":"comic/business-snek/","title":"Business snek (Someone's been watching movies)"},
{"i":290,"prefix":"wp-content/uploads/2021/03/Twin_Dragons_","pageUrl":"comic/food-truck/","title":"Food truck (The start of Cleo's food emporium)"},
{"i":291,"pageUrl":"comic/the-deal/","title":"The deal (My contracts always make that sound when I slam them down. Yours don't?)"},
{"i":292,"pageUrl":"comic/critical-hit/","title":"Critical hit (9999 business damage!)"},
{"i":293,"pageUrl":"comic/shake-on-it/","title":"Shake on it (The twins would make good horror movie monsters xD)"},
{"i":294,"pageUrl":"comic/gaining-an-edge/","title":"Gaining an edge (Nate: I thought I finally had a use for this contact.)"},
{"i":295,"prefix":"wp-content/uploads/2021/04/Twin_Dragons_","pageUrl":"comic/rock-paper-tail/","title":"Rock-Paper-Tail (No, they did NOT test if tail beats scissor!)"},
{"i":296,"pageUrl":"comic/replacement/","title":"Replacement (Enlisting the komainu boy)"},
{"i":297,"pageUrl":"comic/asian-district/","title":"Asian district (luckily, Kai has no flashbacks to the stairs in the dream chapter xD)"},
{"i":298,"prefix":"wp-content/uploads/2021/04/Twin_Dragons_298-","numlen":1,"idxoffset":-297,"pageUrl":"comic/into-the-lion-dogs-den/","title":"Into the lion-dog’s den (Katsumi doesn't like any of them)"},
{"i":299,"h":1389,"prefix":"wp-content/uploads/2021/05/Twin_Dragons_299-","numlen":3,"idxoffset":1,"pageUrl":"comic/action/","title":"Action (Don't underestimate the cute beast-child xD)"},
{"i":300,"h":695,"prefix":"wp-content/uploads/2021/05/Twin_Dragons_","pageUrl":"comic/next/","title":"Next (Grab fwip grab...)"},
{"i":301,"pageUrl":"comic/and-the-win-goes-to/","title":"And the win goes to… (Come on and SLAM! And welcome to the YEET!)"},
{"i":302,"pageUrl":"comic/emotional-damage/","title":"Emotional damage (He made her sparkles disappear)"},
{"i":303,"prefix":"wp-content/uploads/2021/05/Twin_Dragons_304-","numlen":1,"idxoffset":-302,"pageUrl":"comic/meishi/","title":"Meishi (proper introductions are important)"},
{"i":304,"prefix":"wp-content/uploads/2021/06/Twin_Dragons_","numlen":3,"idxoffset":1,"pageUrl":"comic/paper-plane/","title":"Paper plane (But throwing them as paper planes would speed things up, you know...)"},
{"i":305,"pageUrl":"comic/doing-your-best/","title":"Doing your best (Supportive grandfather is supportive)"},
{"i":306,"pageUrl":"comic/lion-dog-get/","title":"Lion-dog GET! (Smoll Jin + Strong Kai and Kaya = Flying lion-dog)"},
{"i":307,"pageUrl":"comic/sloppy/","title":"Sloppy (The fierce dragons release their prey back into the wild...)"},
{"i":308,"prefix":"wp-content/uploads/2021/07/Twin_Dragons_","pageUrl":"comic/fish-market/","title":"Fish market (Marco is all about the freshness)"},
{"i":309,"pageUrl":"comic/swordfish-at-dawn/","title":"Swordfish at dawn (Dragons battling it out with fishes? Now I've seen it all.)"},
{"i":310,"pageUrl":"comic/lala-and-the-fish/","title":"Lala and the fish (The poor, dead fish had no chance at all!)"},
{"i":311,"pageUrl":"comic/sneaky-planning/","title":"Sneaky planning (something smells fishy)"},
{"i":312,"prefix":"wp-content/uploads/2021/08/Twin_Dragons_","pageUrl":"comic/due-draghi/","title":"Due Draghi (Marco got his priorities straight as well ^^)"},
{"i":313,"pageUrl":"comic/snake-reflexes/","title":"Snake reflexes (Jin needs a bell)"},
{"i":314,"pageUrl":"comic/leafy-green/","title":"Leafy green (Don't fold it into a paper plane, Jin)"},
{"i":315,"pageUrl":"comic/gathering-of-the-witches/","title":"Gathering of the witches (Extra 'eye of newt' in mine, please!)"},
{"i":316,"pageUrl":"comic/treat-or-trick/","title":"Treat or trick (Buying a drink fixes everything, right?)"},
{"i":317,"prefix":"wp-content/uploads/2021/09/Twin_Dragons_","pageUrl":"comic/sundaes/","title":"Sundaes (No pumpkin spice latte?)"},
{"i":318,"pageUrl":"comic/plan-unfold/","title":"Plan unfold (It took her all day to handpick the worst fish heads)"},
{"i":319,"pageUrl":"comic/not-her-boss/","title":"Not her boss (Liz is just like a chihuahua. She also stands up to bigger dogs.)"},
{"i":320,"pageUrl":"comic/dragon-food-trucks/","title":"Dragon food trucks (Please read the fine prints. May not fulfill \"all\" needs.)"},
{"i":321,"prefix":"wp-content/uploads/2021/10/Twin_Dragons_","pageUrl":"comic/short-fuse/","title":"Short fuse (You like Benji? You like Jin? Now we combined them into a super-being a cuteness!)"},
{"i":322,"pageUrl":"comic/lion-dog-marketing/","title":"Lion-dog marketing (Jin could probably sell people car insurance and they wouldn't realize)"},
{"i":323,"pageUrl":"comic/yo-yo-tsuri/","title":"Yo-yo Tsuri (The lion-dog university of Japanese is not accepting new students at the time.)"},
{"i":324,"pageUrl":"comic/skilled-lion-doggo/","title":"Skilled lion-doggo (Jin getting the best yoyo's)"},
{"i":325,"prefix":"wp-content/uploads/2021/11/Twin_Dragons_","pageUrl":"comic/reptile-marketing/","title":"Reptile marketing (Cleo crunching numbers and way too positive views on marketing returns)"},
{"i":326,"pageUrl":"comic/search-mode-engaged/","title":"Search mode engaged (It's not Straw Hat from a certain manga)"},
{"i":327,"pageUrl":"comic/the-reveal/","title":"The reveal (polar bear + hot day = grumpy polar bear)"},
{"i":328,"pageUrl":"comic/favor/","title":"Favor (A polar bear and a snake walk into Greenland...)"},
{"i":329,"pageUrl":"comic/high-standards/","title":"High standards (A Lebeau always pays her debts)"},
{"i":330,"prefix":"wp-content/uploads/2021/12/Twin_Dragons_","pageUrl":"comic/of-fur-and-scales/","title":"Of fur and scales (Rex gets plenty of water to keep him from combusting)"},
{"i":331,"pageUrl":"comic/differences/","title":"Differences (This lasagna isn't going to deliver itself)"},
{"i":332,"pageUrl":"comic/keeping-it-real/","title":"Keeping it real (Kaya notes down: Shake camera for next Utube video)"},
{"i":333,"pageUrl":"comic/witch-hunting/","title":"Witch hunting (Meanwhile, Clementine is directing a 2-hour movie about eating at an Italian food truck)"},
{"i":334,"prefix":"wp-content/uploads/2022/01/Twin_Dragons_","pageUrl":"comic/witch-navigation/","title":"Witch navigation (Do not trust in the Global Witch Positioning System)"},
{"i":335,"pageUrl":"comic/fish-cake/","title":"Fish Cake (Move over, Tony hawk, here's Tony Bat)"},
{"i":336,"pageUrl":"comic/bat-missile/","title":"Bat missile (TAKEDOWN!)"},
{"i":337,"pageUrl":"comic/another-one/","title":"Another one (one little bat, two little bats,...)"},
{"i":338,"pageUrl":"comic/bats-out/","title":"Bats out (Larissa: REEEEEEE!)"},
{"i":339,"prefix":"wp-content/uploads/2022/02/Twin_Dragons_","pageUrl":"comic/youve-been-had/","title":"You’ve been had (Sneaky little batsies)"},
{"i":340,"pageUrl":"comic/influencer/","title":"Influencer (Dinah is definitely the brightest light bulb in existence :p)"},
{"i":341,"pageUrl":"comic/meet-the-cook/","title":"Meet the cook (A dragon lured closer by a polar bear)"},
{"i":342,"pageUrl":"comic/interrupted/","title":"Interrupted (Dads will be dads.)"},
{"i":343,"prefix":"wp-content/uploads/2022/03/Twin_Dragons_","pageUrl":"comic/cousins/","title":"Cousins (Charon is a little accident-prone)"},
{"i":344,"pageUrl":"comic/bat-gathering/","title":"Bat gathering (Their room is NOT the batcave, no matter how many times Charon says it.)"},
{"i":345,"pageUrl":"comic/wolf-spotted/","title":"Wolf spotted (It's not just Charon Rex has to watch out for.)"},
{"i":346,"pageUrl":"comic/above-and-beyond/","title":"Above and beyond (Nate has been waiting for an opportunity to use those pigeons.)"},
{"i":347,"prefix":"wp-content/uploads/2022/04/Twin_Dragons_","pageUrl":"comic/poor-bro/","title":"Poor bro (That's a spicy meat-a ball)"},
{"i":348,"pageUrl":"comic/instawham/","title":"InstaWham (Like and subscribe!)"},
{"i":349,"pageUrl":"comic/rush-hour/","title":"Rush Hour (Doggo's taking it easy)"},
{"i":350,"pageUrl":"comic/avenger/","title":"Avenger (Dinah hacking services, now open for business!)"},
{"i":351,"prefix":"wp-content/uploads/2022/05/Twin_Dragons_","pageUrl":"comic/sleeping-pup/","title":"Sleeping pup (Katsumi watches. She always watches...)"},
{"i":352,"pageUrl":"comic/all-expenses-paid/","title":"All expenses paid (It's pocket change to Cleo, but she cares where the money flows in a business, no matter how little.)"},
{"i":353,"prefix":"wp-content/uploads/2022/05/Mathias_","numlen":2,"idxoffset":-352,"pageUrl":"comic/the-little-spider/","title":"The little spider (The itsy-bitsy spider)"},
{"i":354,"pageUrl":"comic/not-having-a-good-time/","title":"Not having a good time (crawling to school)"},
{"i":355,"pageUrl":"comic/the-new-kids-in-town/","title":"The new kids in town (WAHOO!)"},
{"i":356,"prefix":"wp-content/uploads/2022/06/Mathias_","pageUrl":"comic/they-meet/","title":"They meet (Didn't even spill any web on it)"},
{"i":357,"pageUrl":"comic/hanging-out-after-school/","title":"Hanging out after school (Spider spotted a spider)"},
{"i":358,"pageUrl":"comic/dragon-intervention/","title":"Dragon intervention (Cleo would be like: I take your entire stock!)"},
{"i":359,"prefix":"wp-content/uploads/2022/06/Drago_","idxoffset":-358,"pageUrl":"comic/a-day-out-with-drago-and-viper/","title":"A day out with Drago and Viper (I like to move it move it!)"},
{"i":360,"prefix":"wp-content/uploads/2022/07/Drago_","pageUrl":"comic/future-moth/","title":"Future moth (Let's just hope the smoke is not bug spray...)"},
{"i":361,"pageUrl":"comic/just-friends/","title":"Just friends (Drago is more popular than we thought :p)"},
{"i":362,"pageUrl":"comic/komozilla/","title":"KomoZilla (Yes, her bulb does light up.)"},
{"i":363,"pageUrl":"comic/cousin-meetup/","title":"cousin meetup (Dolphin sounds!)"},
{"i":364,"prefix":"wp-content/uploads/2022/08/Twin_Dragons_","numlen":3,"idxoffset":-10,"pageUrl":"comic/clear-the-schedule/","title":"Clear the schedule (I bet this is the first time you see a snake with a case of bed-hair)"},
{"i":365,"pageUrl":"comic/morning-call/","title":"Morning call (breakfast business talk)"},
{"i":366,"pageUrl":"comic/permission-to-party/","title":"Permission to party (Your present is too cheap! exterminate!)"},
{"i":367,"pageUrl":"comic/driving-a-hard-bargain/","title":"driving a hard bargain (Guess someone will have to smile for both of you!)"},
{"i":368,"pageUrl":"comic/impact/","title":"Impact (Cleo should know better than to question Alex's advice by now xD)"},
{"i":369,"prefix":"wp-content/uploads/2022/09/Twin_Dragons_","pageUrl":"comic/outsourcing/","title":"Outsourcing (Nice try, Cleo)"},
{"i":370,"pageUrl":"comic/party-planner/","title":"Party planner (She has the party hair already!)"},
{"i":371,"pageUrl":"comic/how-to-wake-up-kaya/","title":"How to wake up Kaya (The chocolate bar might survive today!)"},
{"i":372,"pageUrl":"comic/gift-exchange/","title":"Gift exchange (the pink bow makes it fancy packaging)"},
{"i":373,"prefix":"wp-content/uploads/2022/10/Twin_Dragons_","pageUrl":"comic/pyromaniac/","title":"Pyromaniac (The long awaited return of Sabrina, mother of dragons!)"},
{"i":374,"pageUrl":"comic/wise-decisions/","title":"Wise decisions (towering pile of pancakes!)"},
{"i":375,"pageUrl":"comic/poke/","title":"Poke (When you revert back to doing a voice over of the chaos instead of doing something about it.)"},
{"i":376,"pageUrl":"comic/dragon-cake/","title":"Dragon cake (Personal space around Kaya is a luxury even Cleo can't afford.)"},
{"i":377,"pageUrl":"comic/rattle-snake/","title":"Rattle snake (Dragon and snake, comedic duo)"},
{"i":378,"prefix":"wp-content/uploads/2022/11/Twin_Dragons_","pageUrl":"comic/bouncy-castle/","title":"Bouncy castle (Cleo: I can also have it installed by monday!)"},
{"i":379,"pageUrl":"comic/dragon-knights/","title":"Dragon knights (How dare they steal a dragon's hoard!)"},
{"i":380,"pageUrl":"comic/small-complaint/","title":"Small complaint (Cleo: Just do what I do. Ignore them and continue what you're doing.)"},
{"i":381,"pageUrl":"comic/first-clue/","title":"First clue (Queue mythical good boy!)"},
{"i":382,"prefix":"wp-content/uploads/2022/12/Twin_Dragons_","pageUrl":"comic/sphinx/","title":"Sphinx (Jin makes the cutest lion-dog-sphinx-thingy)"},
{"i":383,"pageUrl":"comic/first-riddle/","title":"First riddle (Jin seems to like playing pretend.)"},
{"i":384,"pageUrl":"comic/two-more-riddles/","title":"Two more riddles (To be fair, Kaya's idea wasn't bad xD)"},
{"i":385,"pageUrl":"comic/the-power-of-friendship/","title":"The power of friendship (Friendship is magic?)"},
{"i":386,"prefix":"wp-content/uploads/2023/01/Twin_Dragons_","pageUrl":"comic/split-the-party/","title":"Split the party (Kai collected the canines)"},
{"i":387,"pageUrl":"comic/one-down/","title":"One down (Jin is just relieved he didn't need to devour any of them xD)"},
{"i":388,"pageUrl":"comic/new-locations/","title":"New locations (Safety first. Always buckle up!)"},
{"i":389,"pageUrl":"comic/lucky-bunny/","title":"Lucky Bunny (Don't ask her about her lucky rabbit foot.)"},
{"i":390,"pageUrl":"comic/celebrity-crush/","title":"Celebrity crush (Amy and Rexy, sitting in a tree... How did a bunny and a wolf end up in a tree?)"},
{"i":391,"prefix":"wp-content/uploads/2023/02/Twin_Dragons_","pageUrl":"comic/the-dungeon/","title":"The dungeon (Now the dungeon has an actual dragon in it xD)"},
{"i":392,"pageUrl":"comic/the-library/","title":"The library (*Russian swearing from underneath a desk*)"},
{"i":393,"pageUrl":"comic/archive-dive/","title":"Archive dive (it's only the fifth time those books topple over. It's a good day!)"},
{"i":394,"pageUrl":"comic/genius/","title":"Genius (And another tower falls down)"},
{"i":395,"prefix":"wp-content/uploads/2023/03/Twin_Dragons_","pageUrl":"comic/the-safe/","title":"The safe (First a goat, now a cod. Cleo swears to a bunch of animals xD)"},
{"i":396,"pageUrl":"comic/new-strategies/","title":"New strategies (Something something One Roll Bunny meme)"},
{"i":397,"pageUrl":"comic/running-interference/","title":"Running interference (more internal bunny screaming)"},
{"i":398,"pageUrl":"comic/rewards/","title":"Rewards (Phone: \"We are calling you about your car's extended warranty!\")"},
{"i":399,"prefix":"wp-content/uploads/2023/04/Twin_Dragons_","pageUrl":"comic/undercover-bun/","title":"Undercover Bun (Shocking reveal sounds!)"},
{"i":400,"pageUrl":"comic/roleplay/","title":"Roleplay (Concerned Kai noises.)"},
{"i":401,"pageUrl":"comic/another/","title":"Another (Rex is speed!)"}])
